# use the official gcc image
image:
    gcc

variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    #install build dependencies
    - apt-get update
    - apt-get -y install cmake
    - apt-get -y install libblas-dev
    - apt-get -y install liblapack-dev

build-job:
    # build iceicle and the test suite
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make -j
    artifacts:
        paths:
            - "build/"

test-felib:
    # run the unit tests for the finite element library
    stage: test
    script:
        - cd build
        - ctest --output-junit report.xml -j4
    artifacts:
        when: always
        reports:
            junit: ./build/report.xml
